mdn/workflows

- .github/workflows/auto-merge.yml
- .github/workflows/idle-issues.yml
Adds the `auto-merge` workflow used on a number of repositories
> feat: add auto-merge workflow

- .github/workflows/auto-merge.yml
Fixes `auto-merge` action by defining the `GH_TOKEN` input it will receive
fix #2
> fix: auto-merge action

- README.md
Add usage docs for `auto-merge` to README
fix #7
> docs: auto-merge

- .github/workflows/idle-issues.yml
Upping idle labelling rate from 100 to 300
> refactor: upping idle labelling rate

- .github/workflows/publish-release.yml
Use node-version and not release-type for node-version :)
> fix: relase-please action

- README.md
Add a note to the README with regards to conventional commits and the release please action
> docs: update readme for release please action

- .github/workflows/auto-merge-workflows.yml
Adds an `auto-merge` action reusing the action from this repo.
fix #28
> chore:automation ~ add auto-merge action

- .github/workflows/publish-release.yml
- README.md
- feat:publish ~ enables conditional npm publishing for release please
- update documentation
> feat: make npm publishing in release please action conditional

- README.md
Some quick after-merge updates to fix the readme for the idle-issues workflow.
> Update readme for idle-issues

- .github/workflows/publish-release.yml
The YAML for the publish releae workflow was invalid causing the workflow the fail.
This addresses the formatting issue.
fix #39
> fix:yml - the yaml for publish release was invalid

- .github/workflows/publish-release.yml
No need for expression syntax in `if` conditionals in a workflow file
fix #47
> fix: remove expression syntax in if conditionals

- .github/workflows/set-default-labels.yml
- README.md
Adds the set default labels workflow.
fix #50
> feat: add label manager workflow

- .github/workflows/json-lint.yml
- .github/workflows/markdown-lint.yml
- README.md
- feat: add json-lint and markdown-lint
- add markdown-lint workflow
> feat: add json-lint and markdown-lint as reusable workflows

- README.md
Update `idle` workflow documentation to add `days-before-close`
> docs: update docs for idle action

- .github/workflows/new-issues.yml
Another merge conflict caused a bug. :(
> bug: fix new issues workflow

- .github/workflows/pr-check-redirects.yml
- README.md
- [feat: add pr check redirects workflow](https://github.com/mdn/workflows/commit/4f62e02aa84c3708b19692a4ca7423df982bdd0e)
- [docs: for pre-check-redirect workflow](https://github.com/mdn/workflows/commit/fc073067fc15cd7b78f0c0f3d1705d4848b2f728)
Fix #62
> feat: add pr check redirects action

- .github/workflows/lock-closed.yml
Use the `workflow_call` trigger instead of `workflow_dispatch`, hopefully fixes #71
> Fix #71: use `workflow_call` trigger instead of `dispatch`

- .github/workflows/allo-allo.yml
- README.md
This adds the Allo-Allo welcome bot.
fix #94
> feat: add welcome bot

- .github/workflows/welcome-bot.yml
> chore: add welcome bot

- .github/workflows/welcome-bot.yml
Fixes the welcome bot workflow.
fix #98
> bug: fix welcome bot workflow

- README.md
> chore: fix welcome bot docs

- README.md
Updates the idle workflow's docs.
> chore: update idle workflow docs
