mdn/workflows

- .github/workflows/new-issues.yml
Adds a workflow which automatically adds `needs-triage` label to new issues
> adding needs triage auto labeller

- .github/workflows/auto-merge.yml
- .github/workflows/new-issues.yml
This PR pins actions to a specific commit of that action, instead of the development branch.
We should never use an action from its development branch because it can change from run to run. In some cases we can use a release tag (e.g. `v1`), if we trust the owner of the repository (e.g., I expect that GitHub's published actions in the `actions/` org won't be hijacked, or if it is, we'll have bigger problems too). Otherwise, we should pin actions to a specific hash and upgrade if needed.
See [Using third-party actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) for more on this topic.
> Pin actions to a specific hash

- .github/workflows/idle-issues.yml
Update the label from just 'idle' to '🐌 idle' :)
fix #26
> chore:workflows - update idle issue workflow label

- .github/workflows/pr-rebase-needed.yml
- README.md
Created at the request of @schalkneethling (see https://github.com/mdn/browser-compat-data/pull/15931#issuecomment-1111316493).  This PR adds a GitHub Actions workflow to automatically (un)label pull requests that have merge conflicts.
> Create action for "rebase needed" autolabeler

- .github/workflows/publish-release.yml
- README.md
This PR allows passing in custom arguments to the `npm publish` command in the `publish-release` workflows.  This will allow us to hook in BCD, since BCD is designed to build bundled releases (see https://github.com/mdn/browser-compat-data/blob/03ab803b34ba650c1acb91949191ae0d816c5a0a/.github/workflows/release.yml#L24).
> Allow for passing in arguments to `npm publish` in publish-release

- .github/workflows/idle-issues.yml
- README.md
This allows for specific repositories to customize the configuration for idle issue workflow.  The idea behind this is that BCD prefers the emojis at the _end_ of the label.
> Make idle-issues workflow customizable

- .github/workflows/publish-release.yml
- README.md
Make the npm auth token optional for the publish release workflow.
fix #42
> fix: make npm token optional for publish release

- .github/workflows/lock-closed.yml
- README.md
This adds the lock-closed workflow, which automatically locks closed issues and PRs after a year. This was originally posted in https://github.com/mdn/content/pull/14678.
@schalkneethling I don't know how this repo works. Is it automatically run for all other repos, or is this just a common repo, and the workflow have to be copied across (I'm really asking if https://github.com/mdn/content/pull/14678 should be closed because this is the only copy we need).
> Add the lock-closed workflow

- .github/workflows/publish-release.yml
For each conditional check we need to check both the `${{ inputs.npm-publish }}` condition and the `${{ steps.release.outputs.release_created }}` condition.
fix #44
> fix: update condition for publish-release

- .github/workflows/idle.yml
I am guessing that as part of a merge conflict we lost the setting that told the `idle` workflow to not close issues and pull requests.
This fixes this ommision.
> fix: idle workflow should not close

- .github/workflows/idle.yml
Update the idle workflow label and default for `stale-days`
> chore: update idle workflow

- .github/workflows/publish-release.yml
Migrates from yarn to npm.
This currently blocks the release of `@mdn/bob` v3.0.0, which has migrated to npm.
I checked and we don't use this workflow in a lot of repos (I have a folder where I have **all** mdn/* repos checked out):
- `interactive-examples` has an [open PR to migrate to npm](https://github.com/mdn/interactive-examples/pull/2388)
- `data` had never been migrated to yarn in the first place (so it seems)
- `markdown` will be archived anytime soon and won't have further releases
- `bob` has already been migrated to npm
- `mdn-minimalist` has already been archived
See the workflow runs on [this commit](https://github.com/mdn/bob/commit/8df94dd1a08125ce83a55233429726500cfc779f).
> feat(publish-release): migrate from yarn to npm

- .github/workflows/json-lint.yml
- .github/workflows/markdown-lint.yml
- .github/workflows/pr-check-redirects.yml
- .github/workflows/publish-release.yml
This PR bumps the default NodeJS version within workflows to "18", following an MDN-wide upgrade.
> chore!: bump default NodeJS version to 18

- .github/workflows/new-issues.yml
The convention for labels is:
* all lowercase
* spaces instead of underscores or hyphens
We have both in some repos (Yari) and it would be good to consolidate these
> "needs-triage" label should be "needs triage"

- .github/workflows/pr-rebase-needed.yml
The old version of `eps1lon/actions-label-merge-conflict` did not use the standard semantic version, so the [dependabot](https://github.com/apps/dependabot) could not handle the bump of the dependency. So make a manual upgrade for it.
> The new version of `eps1lon/actions-label-merge-conflict` uses the standard semantic version. Which means the dependabot can now resolve the upgrades of it in the future :)
The [change log of the new version](https://github.com/eps1lon/actions-label-merge-conflict/blob/main/CHANGELOG.md#300):
> - Update to node20 (eps1lon/actions-label-merge-conflict#115)
> build(deps): bump eps1lon/actions-label-merge-conflict from releases/2.x to v3

- .github/workflows/auto-merge.yml
Modify the automerge to check on dependabot user instead of actor to prevent force pushes from forks
Make sure automerging only works for dependabot
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1914746
> fix(ci): check on dependabot user instead of actor

- .github/workflows/markdown-lint.yml
- .github/workflows/publish-release.yml
- docs/markdown-lint.md
- docs/publish-release.md
Bumps Node.js from v18 to v20.
Node.js v18 will no longer be maintained after April 2025.
Part of https://github.com/mdn/mdn/issues/521.
> chore(deps): bump node from v18 to v20

- .github/workflows/auto-merge.yml
- .github/workflows/lock-closed.yml
- .github/workflows/new-issues.yml
- .github/workflows/pr-rebase-needed.yml
- .github/workflows/publish-release.yml
- .github/workflows/set-default-labels.yml
Pin 3rd party actions to a commit hash to mitigate the risk of a supply chain attack.
Resolves [7 CodeQL code scanning alerts](https://github.com/mdn/workflows/security/code-scanning?query=is%3Aopen+branch%3Amain+rule%3Aactions%2Funpinned-tag).
Related:
- https://github.com/mdn/browser-compat-data/pull/25793
- https://github.com/mdn/content/pull/38016
- https://github.com/mdn/translated-content/pull/25752
- https://github.com/mdn/translated-content-de/pull/53
> ci(workflows): pin 3rd party actions

- .github/workflows/markdown-lint.yml
Fixes the `markdown-lint` workflow by unwrapping a variable in the `if` condition.
According to [this CodeQL code scanning alert](https://github.com/mdn/workflows/security/code-scanning/10), the condition is always true otherwise.
> ci(workflows/markdown-lint): fix if condition

- README.md
Removes the `allo-allo` workflow from the README.
The workflow was removed in https://github.com/mdn/workflows/pull/153.
> docs(README): remove allo-allo workflow
